name: Rust

on:
  push:
    branches: [ main, ftr-5-combine-github-tasks ]
  pull_request:
    branches: [ main, ftr-5-combine-github-tasks ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    container:
      image:  xd009642/tarpaulin:0.20.0-slim
      options: --security-opt seccomp=unconfined
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Check code
        run: |
          cargo build --verbose
      - name: Test code with coverage
        run: |
          cargo tarpaulin --verbose --all-features --workspace --timeout 120
