name: Rust - Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: coverage
    runs-on: ubuntu-latest
    container:
      image:  xd009642/tarpaulin:0.20.0-slim
      options: --security-opt seccomp=unconfined
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Generate code coverage
        run: |
          cargo --verbose --all-features --workspace --timeout 120
